
sample:
  seed: 2024
  batch_size: 50
  num_mols: 200
  save_traj_prob: 0.00


data:
  protein_path: data/1ka7_B/receptor.pdb
  input_ligand: data/1ka7_B/peptide.pdb # pepseq_RKSLTIYAQVQK  # define peptide: pepseq_{xxxxx}
  is_pep: True
  pocket_args:
    # ref_ligand_path: data/1ka7_B/peptide.sdf # 提供ref ligand的坐标，用于截取口袋区域
    # pocket_coord: [-8.2570, 85.1810, 19.0500] # 口袋中心点坐标
    radius: 10 # 以该中心点为球心截取口袋的半径（单位 Å）
  pocmol_args:
    data_id: dockpep_1ka7
    pdbid: 1ka7


# transforms:
#   featurizer_pocket:
#     center: null # [7.9130, -7.3910, -25.9240]  # space center for denosing, 如果不指定, 则使用pocket的中心点坐标



# The following defines docking task (Gaussian noise)

task:
  name: dock
  transform:
    name: dock
    settings:
      free: 1
      flexible: 0

noise:
  name: dock
  num_steps: 100
  prior: from_train
  level:
    name: advance
    min: 0.
    max: 1.
    step2level:
      scale_start: 0.99999
      scale_end: 0.00001
      width: 3